export const UPDATE_LOCALES = "UPDATE_LOCALES";
export const GITHUB_GET_REPOS = "GITHUB_GET_REPOS";
export const GITHUB_GET_REPOS_FAILURE = "GITHUB_GET_REPOS_FAILURE";
export const GITHUB_GET_REPOS_SUCCESS = "GITHUB_GET_REPOS_SUCCESS";
export const SWITCH_MENU = "SWITCH_MENU";
export const EXCEPTION = "EXCEPTION";
